name: Arduino compile

on:
  push:
    branches:
      - 'master'

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Arduino compile job

    strategy:
      matrix:
        platform: ["esp32:esp32", "esp8266:esp8266"]
        include:
          - platform: "esp32:esp32"
            fqbn: "esp32:esp32:esp32"
            additional-urls: "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"
          - platform: "esp8266:esp8266"
            fqbn: "esp8266:esp8266:generic"
            additional-urls: "https://arduino.esp8266.com/stable/package_esp8266com_index.json"

    steps:
      - uses: actions/checkout@v2
      - name: Setup arduino cli
        uses: arduino/setup-arduino-cli@v1
      - name: Install core
        run: |
          arduino-cli core update-index --additional-urls ${{ matrix.additional-urls }}
          arduino-cli core install ${{ matrix.platform }} --additional-urls ${{ matrix.additional-urls }}
      - name: Install dependencies
        run: |
          arduino-cli lib install AutoConnect
          arduino-cli lib install ArduinoJson
      - name: Compile WebServer example
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./examples/WebServer/WebServer.ino
